default_language_version:
  python: python3

exclude: |
  (?x)^(
    artifacts/.*|
    build/.*|
    dist/.*|
    out/.*|
    \.cache/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: \.(bat|cmd|ps1)$
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
        exclude: (?i)\.(txt|md|yaml|yml|ignore)$|^\.clang-tidy$
      - id: check-shebang-scripts-are-executable
        exclude: \.sh$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [-I, .codespell-ignore]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.4
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|ipp|tpp|inc)$
        types_or: [c++, c]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(cpp|hpp|cc|hh|cxx|hxx)$
        args: [--quiet, --use-color, -p=build]
        types_or: [c++, c]
        require_serial: false
        additional_dependencies: [clang-tidy==22.1.0.1]
