function(learncpp_enable_sanitizers target_name)
  if(LEARNCPP_ENABLE_ASAN)
    if(MSVC)
      target_compile_options(${target_name} PRIVATE /fsanitize=address)
      target_link_options(${target_name} PRIVATE /fsanitize=address)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
      target_link_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
    else()
      message(WARNING "LEARNCPP_ENABLE_ASAN is only supported on MSVC, Clang, and GCC.")
    endif()
  endif()

  if(LEARNCPP_ENABLE_UBSAN)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      if(NOT MSVC)
        target_compile_options(${target_name} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
        target_link_options(${target_name} PRIVATE -fsanitize=undefined)
      else()
        message(STATUS "UBSan disabled under clang-cl/MSVC; enable in the Linux/macOS Clang pipelines instead.")
      endif()
    else()
      message(WARNING "LEARNCPP_ENABLE_UBSAN is only supported on Clang/GCC.")
    endif()
  endif()
endfunction()
